name: Build and Publish Iconify API Container Image
description: Build and publish a container image to Google Artifact Registry

inputs:
  project-id:
    description: 'GCP Project ID'
    required: true
  gar-location:
    description: 'Google Artifact Registry location'
    required: false
    default: us
  repository:
    description: 'GAR repository name'
    required: false
    default: flume
  image:
    description: 'Container image name'
    required: true
  tag:
    description: 'Container image tag'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: ./Dockerfile
  directory:
    description: 'Build context directory'
    required: false
    default: .
  arguments:
    description: 'Additional build arguments'
    required: false
    default: ''
  environment:
    description: 'Deployment environment'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/997168045740/locations/global/workloadIdentityPools/gh-oidc/providers/gh-provider'
        service_account: 'production-github-actions-sa@flume-main.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Build and Publish Docker Image
      shell: bash
      run: |-
        chmod +x ./.github/scripts/build-docker-image.sh
        ./.github/scripts/build-docker-image.sh "${{ inputs.gar-location }}" "${{ inputs.project-id }}" "${{ inputs.repository }}" "${{ inputs.image }}" "${{ inputs.tag }}" "${{ inputs.dockerfile }}" "${{ inputs.directory }}" "${{ inputs.arguments }}" "${{ inputs.environment }}"